import json
from openai import OpenAI
import re
import os
import random

# Set up your OpenAI API key
client = OpenAI(api_key='doesntmatter', base_url='http://localhost:1234/v1')
#openai.api_key = "YOUR_OPENAI_API_KEY"

#def generate_story(prompt):
#    response = client.create_completion(model="text-davinci-003", prompt=prompt, max_tokens=2048)
#    return response["choices"][0]["text"]

def query_ai(question):
    sysmsg = """You are a helpful assistant who is an expert in summarizing and answer questions about lore you hold in memory.
        You will be provided a sentence or sentences, and a context that represents mythology or "lore". Please generate a relevant question about the sentence(s) provided to you, and generate a concise answer to that question based on the lore/mythology provided.
        The question you generate should be directly related to the sentence(s) you are provided.
        It's critical that the question and answer you generate be on the topic of the included context.
        Please make sure your answers are BRIEF and NOT REPETITIVE. 
        Never respond with ANYTHING other than the QUESTION/ANSWER you create and under no cirumstances will you repeat the request, prompt input, or summarize what you did.
        Make sure your response only follows this example: '''QUESTION: is this a sample question about the content? ANSWER: this is a sample answer about the content.'''. Your response will ONLY ever follow that format.
        Always ensure that "QUESTION" and "ANSWER" are capitalized.
        """
    response = client.chat.completions.create(
        model="local-model",  # Or use your local-model if available

        messages=[
            {"role": "system", "content": sysmsg},
            #{"role": "system", "content": "You are a helpful assistant. You are an expert at dissecting language and stories to break them down into their constituent pieces or ingredients. You are an expert at identifing people, places, concepts, ideas, history and mythology, etc in a body of text. You will follow the user's request precisely. You will never create json data with keys that are meaningless things like pronouns. all json keys will be SINGLE WORD KEYS in any thing you generate that contains json. all json you create should be valid, well-formed json. JSON keys should NEVER have abbreviations or contractions or apostrophes or any special character in them. You will NEVER EVER provide to the user anything other than a strict JSON representation, not even commentary to explain the JSON. If you encounter a situation where there is no data to provide for the keys in question, just provide an empty json array as the value (rather than null)."},
            {"role": "user", "content": f"{question}"}
            ],
        temperature=0.7,
    )
    return response.choices[0].message

def process_file(file_path):
#    with open("synthetic_data.json", "r") as file:
#        synthetic_data = json.load(file) if os.path.exists("synthetic_data.json") else []

#    with open(file_path, "r") as file:
        #ext = file.read()
    text = """
The following is the account of /u/throawaylien.

Throaway account, because I'm afraid.

I was first "abducted" in 1987. I was 12 years old. I say "abducted", but it's not like that. Actually, you go willingly. It's scary but it's exciting, too, and they are somehow able to make you feel ok about things. It's not until later that you feel bad or like you've been violated. And they don't do a lot of probing, like raping, or anything like that. That's HOllywood nonsense. They look inside of people sometimes, but they have machines that do it. Not really "machines", but it's like a room where things get done and the walls are...It's hard to explain, so just imagine that all the walls are kind of like x-ray machines? That's the easiest way to describe it.

Sometimes there would be others there and they would be looking into them or they'd put them under and cut them open, but not usually. They took tissue samples from all of us, I think, and they never put your under or give you any anasthetic or anything. They just poke you. With like those things they take samples of the ocean floor? LIke that, but really small. They pull out chunks of you. It's usually done on the butt or on the lower back.

Mostly they talked with me. Just questions and they'd show me things, like television shows and things, and they'd ask me questions about them. I think the walls measure our reaction to things, too, same as they take x-rays. I don't know that, but it's the feeling that I got. They NEVER let you ask questions about what they are doing. Even once I got friendly with a few of them, they just do not like it when you ask them questions. They hate it.

You can't understand their language. It just sounds like "hmmmmmmmmmmmmmm". I'm positive that we'll never be able to communicate with them in their language. I should mention that these are the "grays" that you hear about, except they aren't gray. They are sort of beige, and it's clothes anyway. They aren't naked. I don't know if there are others. People say there are, but I've only ever met these. Anyway, you cannot understand them but they can understand you. And they can put thoughts into your head but they can't hear your thoughts. You have to speak to them. They cannot hear very well, or else they are not good understanding English so you have to speak loudly and slowly. I don't know if they understand other langauges, but I'm pretty sure they would. They are interested in all of us, in everything that goes on. They like a lot of things about our culture, too. They like some of our music. Bluegrass is their favorite so far as I've seen. They like it a lot. They LOVE that african instrument that looks like a gourd with 13 strings. LOVE IT. But they cannot stand horns or horn music, so they hate classical music and jazz. I think trumpets sort of sound like their language? It's a feeling that I get, but I've never been able to ask them.

They've taken me up just about every two years, I'd say, since 1987. Just about. Sometimes it's more often, and I didn't go up at all between 1995 and 2000. They usually keep me for what feels like a day, but it turns out to be about four hours. Usually. The longest I stayed with them was three weeks. During that time, they made me make phone calls and "keep up appearances". They aren't really bad...well, i was going to say "people". But they're not really bad people. Or whatever.

The two that I got sort of close with told me to call them Jack and Gina. I don't know if they are male or female or even if they have different sexes. But I know that those aren't their real names. Those are just names that they told me.

They will make contact with Earth on a wide scale in 2021. That's the year when they'll land here, or colonize, or whatever. I'm not exactly sure what their plan is. They don't seem to be evil or dangerous. Their planet is, so they told me anyway, a very long way away. They couldn't explain to me how far, they said, becuase it was too far for me to understand and it was also "close to the side". I have no idea what that meant, but it's always stuck with me. Home is "Too far away for you to understand, but also close to the side." We don't have anything that they want, so they told me. So I don't really know why they come here or why they've taken so many of us up or why they've gotten to be friends with me. They do not have any religion and they don't need oxygen or water or trees or anything, I don't think. They don't eat people. I don't think they want to breed with us or genetically engineer us. I don't know what they want. But they've been coming here for I'd guess at least 10 or 20,000 years. I'm not very good about history and "upper paleolithic" and all that. But they've got video of all sorts of stuff and they showed me video of neanderthals and cro-magnon (which really were JUST like us humans except they all had black skin, way less diversity) and all sorts of other human-like things, Us's, or whatever. And they showed me video of the pyramids being built and this HUGE stone building that I guess is lost somewhere or was destroyed but it was in Europe, I could tell from the video. They have video of them talking with all sorts of people all throughout the history of Earth. They showed me some of them and asked me questions about them but I couldn't understand any of it because I only speak English and even English from 200 or 300 years ago is so different that I could hardly understand it. So I told them that they probably knew more about it all than I did.

I was up three weeks ago. That was the last time. I'm pretty sure that I'll go up again in a couple of years, but I'm not sure after that. The whole "program" or whatever they call it is going to change in July, 2021. I think they said 8th, but it could also have been 18th, I wasn't hearing very well. They weren't trying to intimidate me or even to warn me, so I don't think we have anything to worry about. I hope they don't show the videos they took of me when they first started taking me up, becuase I was so scared and young and they are embarrassing.

Edit...I changed an accidentally racist bit in there that someone pointed out. Changed "They were all black" to "all had black skin, way less diversity".

Edit....No more questions. They are not happy with me. Sorry.

I can't even understand Scottish people TODAY. It sounded a lot different even 200 and 300 years ago. And it's not like they only take people who live on my block.

Ask me these questions after you've been in the same or similar of a situation. Edit--also, I mentioned somewhere else, but they almost never come to get me at my house and I'm never asleep. i don't know why people always claim that this happens when they're asleep, but I usuallydon't believe those people.

I could talk about all of it, I guess. I'm afraid of people, not of aliens.

"Imminent" is not really the right word. The better word is "July 8th or 18th, 2021". They were very clear about that, and they have been since they first took me. They have accents, difficulty with vowels might be a better way to say it, so I can't be sure if they're saying 8th or 18th. It sound like "aaiitee" no matter if it's 8 or 18. I would guess it's some sort of planet alignment or start alignment thing--I don't know--same way they can only launch space shuttles on the right day because of atmospheric conditions and gravity. I'm not a physicist, so I don't understand it.

Reading and hearing are two different things. I can't even understand Scottish people today, or people with really thick appalachian accents. I don't read a lot of Shakespeare, but I've heard that it takes quite a bit of study to understand what his double meanings and stuff actually mean, so I'm not sure that's a good example. Anyway, I answered someone else on this question, and it's not like they only take people from my block or my town. A guy videotaped two or three hundred years ago from northern Canada or London, it's really difficult to understand them. Plus they're often scared, often crying. They have tapes--tapes is not really the right word, I know--of people from all over, but they only ever showed me people speaking English and then a few times they've showed me people speaking other languages, but I think just to test my reaction.

I don't know. I've seen footage of building, and footage of them being used, but I can't tell you "how". I'm not an engineer. I am pretty sure of this, though, that they've only ever observed. They've taken a few of us and they've taken a few of us for good, too, because I know there are some of us that have gone back with them. But I don't think they've ever taken any sort of action on our planet. They don't control the weather, didn't build the pyramids, and they didn't give Hitler instructions. I think the ones who take me are sort of like college students. I know this sounds silly, but it seems like the ones who come here are doing research and maybe even writing home about it.

I made a throaway account because no one believe this and everyone would think that I'm crazy. And you know what, it wouldn't be any better in 2021 after everyone knows. They would just ignore me.
It's all true.

I just looked it up and I'm going to get it on Amazon.

Answered this somewhere else, but my Internet connection sucks, so sorry if I'm answer it again. I don't know "how" they were built. I'm not an engineer or an architect. I can tell you this, though, it wasn't slaves. There was a town right there where all the workers lived. There was a lot of singing and at night there was dancing and what looked like bonfire parties. The big blocks of stone came in off a river that was there, which I guess was the Amazon. It came right up to where they were building, though, so it was probably a canal or else the river moved. And one thing is this, when you see picture of it it's always guys pushing big blocks up ramps around the outside of the pyramids, but that's not right. The blocks went up inside the pyramids. I don't know if they had ramps inside or elevators or something, but they pushed the blocks inside the pyramids and then at the top they came out at the corners. Also, becuase people always care about this, there were no white people there. There were some black people there, but mostly they all looked egyptian. Kind of brown, kind of olive. That's all I remember from that video. The better video was the one in Europe. It could have been Russia, I guess, but it looked like Europe with the same kinds of trees. With the pyramids, I wouldn't even have recognized it if it weren't for the pyramids because it wasn't a desert. But the one in Europe or in Russia is ENORMOUS. Very big. I have never seen it in real life, or heard of it, or anything, so maybe it's been covered up with a forest or with a city or something. It's not a pyramid, though, it's a big complex of stone buildings, some are square and some are pyramids, and some are circles that are open in the middle like gardens and the walls are all held up by stone arches. Beautiful place. There was no video of that one being made, just of the complex. At least I haven't seen it being made. I hope there are people looking for that kind of thing, becuuse if we found this one it would really be neat.

I answered this in a little more detail in another question.

WTF!!!? Seriously! What's the name? Edit--I looked up that Croatian one and the picture was a step pyramid, so it wasn't the same. But it looks to be about the size of the one in the complex.
No. No Stonehenge.

No. I don't think they know? I'm not sure how they would know.

I know three other people who are taken up as regularly as I am, and we've talked about ICAR. I've never been in contact with the ICAR people and, to tell you the truth, I don't think ICAR is necessary or real. Maybe other people's experiences are different, but I don't think it's that traumatic. Neither do my friends. (I'm not sure "friends" is the right word. We met on a ship and we're sort of in contact, but we don't see each other ever.) It's not normal and it's scary as hell, but there just isn't all the probing and the "mindscanning" stuff that is on the ICAR site. And all that talk about alien-human hybrids is...I don't know. Fun, I guess, and it sounds an awful lot like X-Files, but it's not very real I don't think. The gray guys--by the way, they aren't really all that small, they're about the size of a small woman--can sort of zap ideas and words and thoughts into your head. But they can't read your thoughts. They just can't. I've thought some awful stuff while up there and they've never said anything about it so I don't think they can read thoughts.

Yeah, I guess so. I hadn't thought about that because all that stuff down there is not so old. But the pyramids in Egypt weren't all alone out there, either. There were buildings all around them where the workers lived and there was a town right by there. So, you know, it looked different. But this thing in Europe, or I guess in what I thought was Europe, was HUGE. And, you know, I guess maybe it could have been Mexico or India or Australia or who knows where. But it looked like Europe or Russia at the time. Lots of forests and trees like you'd see in Russia or Canada, that type of thing. Anyway, human people built them. The aliens didn't. They just watched.

Oh, I'm a dope! I meant Nile. The Amazon is on a different continent. That pyramid link is neat, though. The video they had didn't show what was inside the pyramid but that picture on your link looks like it could have been what was going on inside there. The complex didn't look anything like that Tenochtitlan recreation, but that's the same idea. The pyramid wasn't a step pyramid. It wasn't in the center, just like the one there in Tenochtitlan wasn't. And the main building, or what I took to be the main building, like an office building, was a lot like that flat rectangle one in the corner of the Tenochtitlan picture, but HUGE. Really big. And there were those circular structures, and I think they were the "big draw" or whatever that people came to see and be impressed by. I think people walked around in the circles for some reason and then had parties in the big gardens in the center. I don't know, though, that's just me guessing.

Just from what I read, I think that half of the stuff out there is probably outright made up. The other half, I don't know. I wouldn't believe it at all from what I read. Maybe people are traumatized by it and that changes their memory of it, like the way they remember it. I don't know. Here's another thing that I should have mentioned, it never happens when I'm asleep. I don't really believe these stories that start "I went to bed" or if it's about an abduction in a bedroom. I don't believe those. I am always awake and I'm never in my house. I don't think they've ever come into my house to take me. But they don't schedule it with you ahead of time, either, I don't mean that.

No one believes it. I know that. But, it is or it isn't, you know? If I were Jesus or Obama or Michael Jackson or something then maybe I'd try to tell everyone. But it wouldn't do any good. Whatever is going to happen in '21 is going to happen. I'm not afraid of it, but maybe I should be.

Nope. I'd say it looked most like the Egyptian pyramid. Just flat sides. But it was way taller and it seemed to be skinnier. Or more narrow. Everyone is so interested in this pyramid! It was more of a complex, anyway.

Willingly, yeah, like you get up and walk. There's not a lot of fighting and wrestling. Nothing like that. I suppose if you tried that, then they might get rough with you. But I don't know. And, yes, crying. It's scary as hell. I've said that over and over again. It's not traumatic, I don't think, though as I've said it might be for some people. But it's still scary the first time, or the first few times. I guess I should be clearer about fear and being scared? My point is that you aren't afraid that they are going to kill you, and there's no probing, no raping, nothing like that. It's scary because it's, well it's just scary. But, at least for me, I absolutely knew the very first time that I'd be coming home, that they were't going to kidnap me or kill me or anything like that. It's like going to the hospital, or like taking your dog to the vet...you go willingly, but it's still scary. And, yes, "used". What's odd about that? I'm not sure exactly why that's funny. I'm using a building right now. If you're thinking like using pyramids for space travel or to communicate with Mars or something, that's all Hollywood nonsense and that's in your head.

As for a coverup? I'm not sure that there is a cover up. I don't know that any any government know, like really know, what is going on. It wouldn't surprise me, but I haven't seen any evidence of a cover up. I've never once been taken up to have tea with Jimmy Carter, for example. Having tea with Jimmy Carter isn't something that goes on up there. But, I mean, even in this thread there's plenty of evidence for why they might want to cover up this. It's because people can't handle it. People can't believe that they're not alone. Can't believe that there's something up there that's smarter than us but that isn't God? I don't know.

Their agenda is really the more interesting question. Unfortuantely, I have no idea what it is! I really can't even guess. They don't seem to be evil or anything like that, so I don't think they want to farm us or use us to make some super race or slave labor. They have never asked me, for example, where to get gold. They've asked me about money and about gold, but more like they were just asking and interested, not like they wanted our gold. They don't seem interested in water or wood or diamonds. I have no idea what they want. Sometimes I think that maybe they just want to be friends, but I know that can't be true because they aren't really friendly. But there is this. They always, always, always make a big deal about giving me a bowl of salt when I'm there, like it's a gift. Now, I think that they're confused about us, like we want salt as a gift. But I guess maybe they love salt? Maybe they're after salt? I don't think so, though. I think they just think it's polite.

I understood why you were asking. I just don't know anything about a cover up. If there is one, then I guess it would make sense that the government wouldn't know to tell me to shut up because I don't really talk about it.

That's what I thought about the salt. I just can't tell whether they think it's a great gift or whether they think that I thnk that it's a great gift. Either way, i usually smile and taste a little bit and then that's the end of that. As for appeasing me...yeah, they don't seem to interested in that. They're in charge and they know it.

I think my tone is so different because most of these stories you hear are actually nightmares. That's what I believe. A lot of people think that they're abducted by aliens and probed and stuff, and it all just sounds so much like a nightmare. I think it's people looking for attention or maybe who have had nightmares and really believe that they've experienced something real. And there are some people who are kind of crazy, too. My friends, the ones who I'm sort of in touch with every now and again, have all wondered if they were schizophrenic and one even talked with his cousin who is a psychiatrist or psychologist, whichever. The kind that goes to medical school first. The thing is that sometimes I hear people talk about abduction and I KNOW that they're making it up. And sometimes I hear people talk about it and I think, yeah, that could have happened. It's odd to me, though, that there are so many stories about people being abducted once and just once. that doesn't seem to be normal to me.

No, the thing that didn't happen the most is Jamie Hyneman replying to a comment of mine.

I have never had anything at all out of the ordinary happen to me. Other than this, I mean. OH! I had a baby tooth that didn't fall out until I was in my late 20s! That's a little odd.

I get that you don't believe me, and I don't blame you. I wouldn't believe it, either, if I'd never experienced it, I think. Anyway, July of 2021 and you'll change your tune.

I don't think either. I don't think they want to help us or get rid of us. It really bothers me, to tell you the truth. What bothers me about it is that I don't know what they want. I feel like they aren't going to kill us all or enslave us. I just don't believe that's what they're after. I think my best guess is that we're kind of like rats in a lab. or dolphins? We study dolphins all the time but we aren't trying to kill them or help them just study them. That's what I think. I hope. I have never seen a single weapon while with them, or at least nothing that I could identify as a weapon.

I really didn't phrase that well. I think i should edit that. I mean that they look just exactly like we all do today--not like the other people who looked more like apes, or like neanderthals who looked more like gorillas-- except that they all were black and there wasn't much difference between them all. I really, really didn't phrase that well.

Now when it happens I feel annoyed more than anything. I don't know how long it will take and I can't say "OH, how about next week?" at first it was nervous, though, and scared a bit. But like I mentioned earlier, it was scared liek scared when you go to the doctor. I do get a feeling like my skin is tacky or sticky, and my hair stands up on my arms and legs and all over. But that's only on the ship, so I think it has to do with the machines that they have or maybe they use magnets or something. No idea there. But "feeling"? It's more anxiety than comfort, but it's not too bad anymore. I have to admit though, I'm awful skeptical of channeling. I don't really believe it. But I know that when I'm on the ship, they can put words into my head. So maybe they can do that over a really long distance?

I have never seen the big ship from the outside, so I don't know what it looks like. The little ships don't have windows, so I can't see out. The little ships are the shape of hot dogs, sort of. Boy, this sounds stupid, but kind of like VW microbus vans, but a little bit bigger. The outside is a kind of gun metal blue that looks wet, glassy. They use those to come to Earth. They never communicate to me that they're going to pick me up ahead of time. Which would make my life a lot easier. I usually know that they're following me because my radio doesn't work if I'm in my car, or if I'm on the phone I'll have a lot of dropped calls. Now because it's happened so much and I'm used to it , I don't put up a fight. I know they're there, so I park and wait for them. The first time it happened I was 12 and they took me at about 8:30 at night. I was in my back yard and my mom was out of town on a business trip. My dad was inside and he was pissed off when I came home. Anyway, they do it jus tlike you'd think. They wait until I'm alone and then they come and get me. If I'm at home, they knock on the door. That's ony happened once, though. If I'm out for a run at night, they wait until I'm alone and then land and one of them motions at me or says 'Hi, Throwawaylien, it's time for a trip". It's never, ever, ever more than two of them on the small ships. Gina is always there and has been for the last ten or fifteen years. Inside the small ship there are two seats in the middle that face each other and that's where they sit. The sort of "back half" of the vehicle is closed off and I can't see in there, but I'm pretty sure the engines are in there. All along the rim of it on the inside is a bench. It's metal, or something like metal. I have never seen a comfortable seat or chair or bench up there. They all sit on flat, hard surfaces, so far as I know. The ships are lit on the the floor and on the walls and there are no light fixtures anywhere. There's no radio, no nothing. I think those ships are remote controlled. Inside the big ship is a lot different.

Woops. Anyway, as I was typing.......Inside the big ship is completely different. The little ship docks in the ship. The end where there is no engine, it opens up and that's where we walk out. There's a series of bays where these little ships dock. We walk out and through a little hall and then that opens into a big room where they work on small ships and have projects going. I've never been to the other side of that room. Off to the right...and it's always to the right, so we must always park int he same place?....is a waiting room. That's where we go immediately. I sit there. SOmetimes there are other people there. That's where I met my friends that I mentioned earlier. People there are usually scared. There are five doors off the room, arched doorways with sliding doors, but they are NOT automatic doors. They have to touch a button for them to open. I can do that, too, so it's not like a fingerprint scanner. One of those rooms I've never been in, but the other four I know are exam rooms. That's where we go in and they ask questions, where the walls are like x-ray machines. Sometimes they show videos on those walls, too, but usually not. OK, after that there is another room and the door to that room is on the other wall. So imagine you walk in on the west side, the five doors to exam rooms are on the east side, and then this door is on the north side. I know directions make no sense up there, but I'm trying to explain it. The north side door opens up to a big medical room. That's the only place I've ever seen them do anything bad at all. And that's where people are really scared. A couple of times I've seen people sitting up on tables, but they weren't doing surgery or anything. It's in that room that they stick you and take a tissue sample. Usually they tell you what they are doing. That room has a door on its north side, too, and it opens up to a different waiting room. It's pretty relaxed in that room. Ok...lights, all on the walls or on the floor, never seen a light fixture. Seats are all benches, all built into the wall or the floor. There are a few cabinet looking things in the medical room, but that's it. No computers, no terminals, nothing like that. In that waiting room there are a couple of places for us to sit and drink hot water. I don't know why, but they give us hot water. And off that room is the room where we meet with them and they really talk, ask questions, show us things. In that room is a table not for people to lay on but that we sit at. There are usually two of them in there, but not always the same ones. I go in, I sit down, they offer me some salt, then they show me a video or ask me a question. Sometimes they have different kinds of food that they show me and ask me about. That's about it.

OH! Wait, also there's a hallway of dorm rooms. Dorm rooms? I guess that's what you'd call them. They have blankets and a toilet bucket. They also have a big tank of water like one of those culligan tanks, except it's like the water holds itself together naturally, like there's no plastic around it. There are usually a couple of books or magazines in there and a flat hard bench to sleep on. No pillows. Sucks. That's where you get stuck if they want to keep you. If you need anything or if they need you to do something, they walk you back out tot he little ships.

I don't mind answering. They do seem stiff and logical and all that with me, but that may be just because they're working. Like I said, I'm kind of close to a couple of them, and by that I mean that I've told them some jokes and they kind of chuckle, though i don't know if they get it. And sometimes they look at me and I can tell that they feel something like sympathy or kindness to me. Physical tests...not much. They stick me for a tissue sample each time. They've taken hair. They do the x-rays sometimes. They've asked me to pee in cups and to ejaculate in a cup. I've heard people tell stories about them presenting abducted women for that, and that's all fantasy. It's just like a doctor's office, they give you a cup and tell you to do it. If you can't, they'll give you some privacy. OH! There is one thing, they do touch you all over and make you open up your clothes when you leave, but I think it's because they want to make sure you don't have any of their tools or anything.

Oh yeah, I've seen lots and lots of other humans. And like I mentioend I've seen lots of videos of other humans. You know, I wonder about whether or not they all look exactly alike. To me, yeah, they pretty much do. I can tell a little difference in Gina because he (or she?) has a scar or what looks like a scar on the right hand. Oh! That's a good thing to mention...they are human-like, two feet and two eyes and all that, but they only have three fingers. Long, ugly fingers. There's a thumb-ish thing, too, but it's pretty short and it's more like a stump. They aren't all the same height, but I don't know if the shorter ones are female or male or something like that.

Will reply tomorrow. Am sleepy.

Will reply tomorrow. Am sleepy.

No. I saw that page and those pictures already and said that it was not the same.

We'll be fine, I'm sure. I hope.

No idea. That's a fun question, though, I guess. OK...when I was there the longest, which was about three weeks, there were at least 10 people there during that time. So I guess maybe let's say 120 people a year? They might have more ships or more holding areas on their ship, though. Or they might take time off?

No, I don't think that I could refuse. I'm not sure how one would volunteer. Next time I'm up I'll mention Studebaker_Hoch and see if they're interested. :)

I was kind of afraid of this question, because you're going to think this is crazy. But they do two things. I have never seen them hug, but sometimes they will touch each other on the small of the back, or where the small of the back is on humans, like the lower back. And when they meet each other, I've seen them do this thing where they touch the back of their hands together, sort of halfway in between a backward handshake and a fistbump. They've never done either with me.

I don't know how many videos they have. Or how much video they have? But they don't have footage of, like, the Kennedy assassination, just to pick something in the news right now. They might have it, I guess, but I haven't seen it. All that I've seen is very boring, very run of the mill. It's like videos of your uncle working on his motorcycle, or a guy herding sheep. Very boring stuff, mostly. They pyramids are pretty exciting, but the video was more about people living together and building something, not about BUILDING THE PYRAMIDS!. If that makes sense. They do watch our TV and they ask about it. I think they ask mostly about the things that they can't quite understand. I'm always a little afriad that if we're doing a TV session that I'll hear the X-Files theme. I'm not sure how I would handle that.

The tissue sampling is a bit painful, but it's not much worse than getting a shot. It doesn't leave any marks at all, so far as I can tell. I've got a bald patch on my arm from a test they did on me, but that's not a big deal. But who knows what I look like internally. There might be big changes internally that I don't realize.

Thanks?

They've never initiated a handshake/backhand thing with me. I would do it if they did, though. I've never tried to touch them, either. One of my friends has, she says, and she says touched hands with them and felt their head and also taken one of their hands and put it on her own hair to feel. Touch is a really sensitive thing.

No health problems that I know of, or that I"m willing to talk about anyway.

The little ships...well, I guess all that ships, actually...feel very sterile. They feel like they are super super clean. I don't know if they are. I've never stopped to think about that before, to telly ou the truth. But the ships always feel very clean, so maybe they are taking precautions that I don't know about. And I guess it's also possible that we just don't get the same diseases.

Yeah, these three people who I call my friends because have each other's phone numbers and we talk sometimes, we all met on a ship, but not at the same time. I'll make up names for them so that I can talk about htem a little easier. I'll call them Coach, Sam, and Diane. I met Coach first. He's about my age and he is from the US, but I don't think I should say any more about where he's from. He is a minor celebrity, actually, so best just leave it at that. He had been up a few times by the time we met. Sam is ten years older than I am. He does not live in the United States but he does speak English. We met on my fourth or fifth trip. And he was up at the tail end of my long three-week stay, but we just waved at each other in the hallway. Diane a minor, so I shouldn't say anything about her. But I met her up there when she was four. I've never had children and don't think I ever will. So I'm sort of Diane's uncle...in a non-creepy way. Diane's father is not in the picture, but her mother and step-father know about the abductions. I've been to their house several times.

I don't understand the first part of the question. The second part, I don't know. It could be spinning, I guess. I'm not sure even how high up we are. We could be in space or I guess we could be like where satellites are.

Ok. I get that. Well, it's the whole like third of the small ships that opens, so it's not exactly like a hatch, I guess. But there's a godawful loud noise when it does, which I always assumed was pressurizing or depressurizing or whatever. I have never been or felt weightless except on the return trips it feels like you're on an elevator that starts really quickly. And no, I've never had to be restrained or to wear a seat belt. Like I said, though, the only feeling of motion is the dropping feeling when we come back. Although now that you've mentioned it, I don't know if it's actually DOWN or not. I'll ask my friends if they know. Yeah...'Close to the side.' No idea what that means. And I can't really understand interdimensional travel or materializing out of thin air. I mean, I just can't understand that. So if that's the case, and I guess it might be, then you'll have to wai tto ask them! Or else maybe one of the other people they take will come forward and have a better understanding. As for the interior, I haven't seen any pipes, no cables, but htere are a lot of lights. There are lights all over the place. The ships are very very simple, very empty and plain. There are some signs of wear, but it's mostly just empty and sparse.

Tough to say. I think that, yes, it's possible. There could be crazies out there. But the ones who take me are just very cold and professional. It seems like coming here would be really expensive, or very difficult, and so I don't think they could just come here on a whim and murder for fun. But maybe. I guess what I'm saying is that I get the feeling that organized backing is definitely necessary, but that motives could be different?
Lots of questions here. Well, most of the vids that I've seen are aerial. But they get down ont he ground sometimes. And the videos of people talking, answering questions, are all taken on the ship. Their body language is really stiff. Not sure how to describe it. Put an alien head on a pencil and stand it up, there you go. Except this really needs to be mentioned, that their heads are not so big like in the movies. They are bigger than ours, but not huge. Their eyes are bigger, too, but not enormous lik ein the movies. They ask me a range of questions. Mostly "WHat is going on here?" What is the purpose of this or that machine? Stuff like that. I don't think that they recognize our stereotypes of them as them. They got me one time when I was wearing a t-shirt with one of those huge alien heads on it, like a cartoon. They didn't say anything about it. So I'm not sure that they recognize that image as themselves. ANd, you know, it might not be them, I guess! They have showed me clips of 2001 and asked about the light, the computer light, HAL. They wanted to know if we thought that was a comedy or if it was funny. I said that it wasn't a funny movie. Just to be clear, most of the videos they've asked me about aren't movies or at least aren't movies I've ever seen. They ask me what's happening in footage that they've taken and in home movies that they have, stuff like that. But they've showed me clips of a lot of movies, and here are the ones that I can think of off the top of my head: 2001, like I mentioned, Law and Order, a movie about a basketball player in the 1980s where the actor was Rob Lowe or Robbie Benson, LOTS of clips of westerns that I don't know the names of, maybe even from television shows, and that movie where the girl from Interview with a Vampire is a cheerleader. The salt I just taste like it's normal. I don't want to offend them, and I can tell they want me to taste it or to take it. I went to college for three years but didn't finish because of some family/money problems. So I don't know a lot about history, philosophy, etc. They don't seem interested in philosophy. They don't have religion, I know, becuase they don't understand it. They ask about that a lot. Like "is this an idol?" about all sorts of things. They'll show a picture of, I don't know, a bridge or a donkey or an empty picture frame, and they'll ask "Is this an idol?" Those questiosn are so strange that I sometimes think that they are testing me, not trying to get information. I don't know.
The small ships float and can fly, obviously, but they land directly on the ground. They have no landing gear. The bottom of it is flat so it can land on the ground like that. It smells like bleach on the ships. The guys themselves smell like fruit, like apples and bananas and strawberries. It's kind of unpleasant. But the ships smell like bleach.I've never seen a window on the big ship, so i don't know. I'm pretty sure they have a written language, because there are some symbols on doors, some on some walls, that kind of thing. But they NEVER write. I never see them write anything down. They never carry paper or an iPad or anything. Even when they do exams on people they don't write anything down. And when they take tissue samples they don't label them.
haha. No. They don't look like that. Most of them are skinny, they don't have those big guts. Heads aren't quite that big, either. Noses are way flatter, very small but way flatter.

Lots of questions. No, we could not destroy them. They are extremely strong. Tough to explain how I know that, but you can just tell when they touch you. No idea how they evolved (or were created?), planet, eat, nothing. I lost about 10 pounds over the three weeks I was with them, mostly because I had no appetite. They gave me flat bread, butter, and fruit. That was it. I think they might be vegetarian. (hahah, no I have no idea!) Their voices all sound like sort of in-between male and female in terms of high/low. But the way they speak is forceful, masculine. They have some trouble with vowels. For example 8 and 18 both sound like "aitee", something liek that. I do kind of hear Gina as female, but that might just be because I associate the name Gina with female gender. They didn't give me any magazines at first, then they gave me all sorts of materials. It hink they do that to figure out what turns us on.

Wow. Lots of questions. Hmm... About HAL...>I feel liek they thought it was funny, a comedy. I don't know why, so I just assume that they think it's funny that a machine could think on its own. Whoa...let's back up...I'm not one of the most important people on the planet. There are quite a few of us, I think, who they take up regularly, and I don't think any of us are that special. I could be wrong, though. Ok, back to questions. They'e never asked about nukes, but they've asked me about wars. They have footage of soldiers that they picked up I think during WWI based ont he clothes. British guys. They tore them up with questions, and the guys were very scared. But I think it was the war that scared them. They want to know why we fought and what "I think the result was", but I don't theink they are pacifists. At all. They show no emotion, no reaction at all to most of my answers. They only ever sometimes react with something like sadness.

No more questions. They are not happy about this. Sorry.

Commenting here was a mistake and I wish I hadn t done it. It changed everything for me, not all in bad ways but mostly in bad ways. I m commenting again now because there are people on Reddit and probably elsewhere who are claiming to be aliens or that I am a government agent or an alien agent or something like that and they are all lying. I m talking about the history of the earth guy and the end of an era contract guy. These are hoaxes. They don t know anything and it looks to me like they are trying to take advantage of my story and my life to get attention. I haven t even visited reddit for years and now I ve seen all these posts about my comments. I wish I had never commented at all all but July is so close and I won t be here much longer so what s the point of not talking anyway and I think I owe it to a few people who have meant a lot to me. It makes me angry to see people try to take advantage like this when people have really suffered and really want answers. So I m try to type it all out. Maybe I ll run out of energy or stop caring but I m going to try. I was wrong about a lot when I posted before and I m sorry but I didn t mean to mislead anyone its just that I didn t know what I know now.

After I commented on here my relationship with Jack and Gina changed especially with Gina and it was like it opened a door up for me and I was able to ask more questions and learn from her. And I guess that s good because I was able to learn a lot more about who they are and what they are doing. But in the whole this was a big mistake because it made my life here so much worse than it already was. I messed up big time and I m still paying for it every day and I m maybe going to pay big for it in a couple of days.

I ve been up sixtenn times since I commented on here and it s much more often now because they are almost done with me. I am going up once more this week and that s it. I ll stay with them in the big ship for a while and then I ll go back with them. That s what they ve told me and I know that I don t have a choice about this and I don t care anyway. I don t think they are going to hurt me but honestly I don t know anymore. I ve found out a lot about them and it s not good mostly. They might kill me. I know that, but I also don t think that they ll torture me in any way or imprison me or anything like that. It doesn t seem like them to do anything like that so even if they are lying it s a better deal then I ve got here.

When I answered questions on here before I was afraid of human people here on Earth, not afraid of aliens, and I think I made that pretty clear. I didn t know at the time that they ever did anything that hurt people. I don t think they do it a lot and I really still don t fear that they are going to hurt me. It was because I was afraid of people that I made a throwaway account on here instead of using my real name. I didn t want anyone to find me, obviously, and because I wanted to protect the privacy of one of my friends, who is t my friend it turns out. I wasn t afraid of the government at the time but I should have been. I don t know if the government was monitoring or if that s how they found me but I was abducted by the United States Government in broad daylight in 2015. They never identified themselves but they were pretty clearly Fbi or CIA or something like that and I was in the United States when it happened, so I know it was the U.S. government and not some other government. Whoever they are, but I think I know, they know who I am and where I am. They kept me for three days and tortured me far worse than the aliens ever have. They abducted me again in 2018 at an airport on my way back into the country and they tortured me for 7 days.

I don t think the government found me because of my comments here. They weren t monitoring me and probably didn t even know I existed. Jack and Gina did know what I was doing and that s why I had to quit answering questions last time I was here. I don t know how they knew it was happening right when it was happening, but they knew and they told me to stop. They had to either be monitoring the whole internet or monitoring me and so I m pretty sure it was just me. They are probably monitoring me right now, too. Also while I m thinking about it I think I should mention that Jack and Gina tried to tell me what they call themselves. They don t call themselves aliens obviusly. I can t spell the word that Gina used and I can t even remember what it sounded like exactly but they said that it meant Friends of Friends. I think that was probably a pretty rough translation

They were really, really angry with me and they took me up a couple of days after I stopped commenting here. It s hard to explain but they didn t exactly threaten me but they did tell me that things were going to be different after that and that I shouldn t talk about them anymore and that things were changing. Again they didn t hurt me but I was pretty scared of them for the first time in a long time. I was scared enough of them after that that the first chance or excuse I had I left America for a while but they found me wherever I went. They know where I am all the time I think and that makes me think that I probably have some kind of tracking device in me somewhere. I don t know that for sure but they ve found me and taken me up now in six different cities on two different continents so they must have some way of knowing where I am. Well, I guess technically three different continents.

After posting here I started talking with Gina though and it was different. This is so stupid to say but I think Gina felt sorry for me or maybe I don t know maybe she or he or it actually sort of liked me. But after I got in trouble with them it was different and instead of just showing me things and asking me questions they started letting me ask questions. Gina would even say,  Do you have questions for me?  I don t know why but I never bothered to ask Gina if she was a boy or a girl of if they had boys and girls. It didn t seem important at the time but now it seems like it s important because I don t know whether to type she or her or it or what. That makes it difficult for me to type this and keep on topic so I m just going to say  she  for Gina because that s the name she gave me and I think of her that way. Asking questions and having conversations with them is always very difficult for me and it leaves me exhausted. They just don t understand English well and they say stuff in weird ways very literal ways that don t make sense. It takes a long time to understand one another.

I wouldn t say I was friendly with Jack and Gina ever but it was definitely different. It seemed like they wanted me to ask questions and like they wanted to answer. And I really believed that Gina and I were sort of becoming friends which I know sounds very stupid. But that ended and changed in 2016 when Jack and Gina left to go back to their home and they took Diane with them. I don t know why they went back but it wasn t like all of the Friends of Friends went back. Jack never came back. And Gina came back in 2018 but she was so different when she came back to the point that I wondered if it was the same Gina or if this was like a different Gina and so I even think of her now as Gina 2. They all look sort of the same but with little differences that you can tell, and Gina 2 has the same scar that Gina did, although now I don t know if that is a scar or if it s just something about the way her skin is. Now Gina 2 is very down to business with me and she doesn t seem like she cares at all about me and I don t know if she ever did anyway.

They took Diane away in 2016 and I haven t seen or heard much about her since then but Gina 2 says that I m going back with them the same as Diane did. So I hope that I ll see her again because I got pretty close to her family several years ago. I haven t talked with her mom in a while now and she and her step-father had a falling out but I don t know what that was about. I don t have any of my own family left really and I won t ever have my own kids and Diane means a lot to me.

I was wrong about some of the stuff I told you all when I commented last time and I think I should clear up a couple of things.

First, I m really sorry that I said that they don t hurt people because sometimes they do. I asked Jack and Gina about what they do to people, not just why they are studying me but what they do to other people too. Jack and Gina told me there are three kinds of human subjects that they study. The first is like me who they study over a long period of time and who they talk with and study for a long time. I don t know how I got put in this group or why they would be interested in talking with me more than anyone else. I think it s just luck because they don t treat me like there s anything special about me. I ve asked them and they didn t really understand the question I don t think. Some people in this group have been taken up hundreds of times over 80 years or more but Gina told me that usually people don t get taken up anymore after they hit their forties. At the time I thought that meant that maybe they lost interest in people when they got older but now I think that maybe it s that most people in this group don t live that long. Some of us in this group they take back with them to wherever it is they come from.

The second group of their little experiments are people who probably don t even realize they are being observed at all, never abducted, but watched and studied. I don t think I m in this group and so I don t know nearly as much about it. I guess maybe they are watching me, but I feel like the people in this group they probably watch like all the time and I know they don t watch me all the time. I don t think they do anyway.

The last group is people who they use for physical testing and that usually kills them. Gina said that they don t hurt people just to hurt people, that they aren t mean, but that these people can t survive the testing. I m not sure what it is they do to them but it kills them. I am really, really sorry that I gave the impression that they didn t do this when they actually do. I didn t know about it at the time and I swear that I wouldn t have come on here and commented that they don t hurt people at all when they do. I still don t think people have anything to worry about because they don t eat people, they aren t trying to harvest our organs, they aren t trying to steal our water or anything like that. But they do some bad things sometimes and there s nothing I can do about it and I m sorry that I made people think that they don t when they do.

One other thing I was wrong about was that I think I probably said that Jack and Gina s race that I m just going to call Friends of Friends because that s what they call themselves, didn t make a lot of those movies that they showed me. The Friends of Friends have only been here for something like 3000 years. Before that it there were others here to watch us and I think something bad happened and they were completely killed off by the Friends of Friends and they got earth along with everything else that those others had. I don t know much about those others and this is not a thing I could really ask about so I really filled in some of my understanding here. Whoever the aliens were before, they must have been doing pretty much the same thing as the Friends of Friends because they bothered to take all the videos and everything. But the way Jack and Gina talked about I got the feeling that they didn t care for those others, like the others might have been their enemies or they might have done something bad. When they talked about it, they didn t talk about it like it was just a shift change or something. I m pretty sure there was a war and the Friends of Friends killed all the others. And I m not sure about this either but I think that the big ship might actually have been built or brought here by those others and not by the Friends of Friends. I know that when Jack and Gina went back home for a while, they didn t go in the big ship. The big ship pretty much stays put I think and I ve still never seen it from the outside so I don t know what it looks like. It might not even be a ship, I guess. It could be like an office building on the moon for all I know.

The other big thing that I was wrong about was that I said that they don t have religion. They say they don t but I don t know about that. I know this sounds like they are stupid, and they can t be stupid if they can travel all the way here and have these ships and all this technology, but this sounds pretty stupid to me.

Gina said that there are a lot of different beings out there. I can t remember if she said thousands or millions, but I think she said millions. And there are millions of planets with life on it, she said, and then there are some forms of life that don t even have planets. Some planets have just like fungus on them or some fish or plants. But there are I think she said millions of civilizations out there. Many of them are as advanced as hers she said. She said that there are only 7 planets in the whole world that are like the earth where the dominant life form has the simple problems. She called them the simple problems, not me. She didn t tell me a list of the simple problems, but she told me some of them that were prayer and faith healing and churches and sorcery and magic and all that kind of stuff, mostly all stuff about religion. And of those 7, she said there were only 3 where people experienced deja vu, or believe in prophecies, or that worship idols. We are one of those three and that s why the Friends of Friends are here. That s why the others were here, too, and that s why the next group is coming in July. Gina says that they know that the whole world isn t really what it looks like but it s actually the creation of a single intelligence and that we and everything exist inside that intelligence. I asked her if it was like the Matrix and then I explained to her what that was and she said it wasn t like that at all and so then I asked her if was like when that hospital show ended and it turned out to all be a kid imagining it in a snow globe and she said it wasn t like that either. But she said that it s the one thing that everyone in the world agrees on, all these thousands and thousands of advanced civilizations, they apparently all have proof that the world is imaginary or a dream or a computer program or something. And they study earth and the two other planets like it because they are pretty sure that these three planets and the intelligent life on them are either mistakes, like accidents, or else one of them might be the center of the whole thing and everything else is a mistake or an accident. They want to figure out which is which so that they can better understand the intelligence that creates the world.

That sounds a lot like religion to me. I tried to finish up college a few years ago and I took a world religions course and to me this sounds like religion, but I m not an expert so I don t know. Also I didn t end up finishing college. I only have like three courses left but I m not never going to get there and that bothers me a lot because a lot of people in my family were really educated and were doctors and engineers and I m just nothing special. That s mostly because of this thing that I ve had to deal with as part of my life.

When I look back on all the videos they ve shown me and all the questions they ve asked it s pretty clear that this is what they are studying in me. I should have seen that even before Gina told me but it s hard to think clearly about things like this because it s traumatic. I ve read some of the comments you all have made about me in the last few months and I ve seen a few of you mention mental health stuff, like maybe I m crazy. I m not crazy. I m not delusional or insane. But over the years I ve had to deal with this shit in my life and it s not easy and maybe that s caused me to see things a little differently than they really are. I don t mean like I m imagining things but that I m maybe justifying things or rationalizing them. You have to understand that I don t have my own life, if you can understand that. I m not in control of it. Someone else is. And they ve done stuff to me, like taking me away and forcing me to watch things and interrogate me and all of it, and I don t have a choice. I don t have a choice in it. And I think maybe when I was commenting here before maybe I was putting kind of rose colored glasses on my experience because the reality of it is that my life doesn t mean anything to anyone and I am powerless and it was easier for me to think of Jack and Gina as friendly and as the things they do with me as just not so bad. I don t know what my point is here except that you shouldn t trust most abuction stories. I wouldn t trust most of the alien stuff that you hear, either, because people out there want attention and they are bored or they want to take advantage of you and make you do things and they make stuff up to get your attention. If you ve been through it in reality it s easy to spot the people making up stuff about it. I say this because I saw on one of your comments there s a guy posting that he s an alien named Adam and is going to show every one the true history of the planet through the internet starting this summer and he made his account right after I posted my comments and then started posting recently. At one point he even said that I was part of his scam somehow. That person is full of BS. That s not a real thing and if you believe it then I ve got a bridge to sell you. And I mention it also because you are probably going to hear a lot more accounts of abductions in the next few years because I ve seen many more of us up there than I used to. Things have changed about the way they are observing us and there s a lot more human contact and a lot of those people are bound to mention it to friends or family and then once that gets started the hoaxers and frauds are bound to start popping up. This stuff is really important though and not just for you and for earth but for the people who they are taking. We are people and this is not easy for most of us. It s hard and it s lonely and we don t have anywhere we can get help.

My friend Sam that I mentioned before died in 2016 and I got a chance to meet his mother at the funeral and I think that helped her deal with the loss a little. He was a nice guy. He was the nicest guy I ever knew honestly. He was only 8 years older than me but he died of bone cancer and I wonder if it had to do with, I guess radiation or something, or just something about our experiences up there. I don t know. Or I don t know we are all getting older and maybe it was just his destiny to die like that, but I don t think so and I don t believe in destiny anyway. He was such a nice guy to me and his mother was heartbroken and there were almost no one at his funeral. And of course that s not his real name, as I said last time I changed everyone s name because I m not about to out anyone on here and I happened to be thinking about that show Cheers at the time and that s why I picked these stupid names.

I begged Coach to come with me to the funeral because it was the right thing to do and because I d never traveled that far on my own but he wouldn t and we haven t spoken for years. He pretends like none of this is real and that it never happens. I know that they are still taking him up and I ve tried to reach out to him but he stopped returning my calls. He is really famous now not just sort of famous but very very famous and I know that he s afraid of what this could do to his career, but it s not like I would ever name him so I don t know why he cut me out of his life. This thing that we are all going through is different for each of us and some of us handle it differently, I guess. But to me it felt different than that when he wouldn t go to Sam s funeral it was like I had insulted his mother or something, like how dare I ask him to go to the funeral of some trashy nobody. When really he just had a couple of lucky breaks and that s the only difference between him and Sam. Or even between him and I. I m not bitter about his success but I am so furious with him about the way he changed and treated me when Sam died and didn t even acknowledge Sam or go to his funeral. I know that he will never ever admit to any of this but I also know that Coach was in the same group as me and that eventually they were going to take him back with them. I bet he thinks he s safe from that now because he s so seen everywhere and they wouldn t dare take up a celebrity because then everyone would know but they don t care about that. So live it up now, buddy, because sooner or later you re going to vanish and your truth will come out.

I met three other people who went up regularly over the last 8 or 10 years and made friends with them and I didn t mention any of them last time I commented here because one I had just met and wasn t sure if we were really going to be friends and the other two I hadn t met yet. They are all dead now. Two of them committed suicide and the other one died in a car accident that I m pretty sure was also a suicide.

So maybe you get it now when I say that once you ve been through this you can tell when people are lying. They don t set you back down here with a message of world peace or a warning to stop wars. They don t care about us, not like that they don t. They don t select some old man on a hillbilly vacation to give him a message about how to save the whales or to fight satan. And the fact of it is is that it takes a hell of a lot of patience fronm me to get to the point where I could ask them questions about anything.

This thing has been a part of my terrible life since I was a kid and it s too much to deal with to be honest. I haven t ever been able to hold down a real job and I haven t been able to make real friends or have relationships that meant anything except I was very close to Diane and her family but she s gone now too. Dad died in 2010 and left me our house and a little bit of money. My mom died a long time ago but that s a whole another story. If it weren t for the house and the money he left me I would have ended up on the street and then you all here would never have heard of me and anyone I talked to would have thought I was a crazy homeless man. And that s how most of us probably end up is either living in the street or else driving our cars off of cliffs and taking enough pills to not wake up. I don t know why I ve been able to handle it and other s can t. I don t know why Coach can handle it and others cant. I don t know what makes us any different or what makes us similar. And maybe we can t handle it better anyway and maybe the better way is just to go out on your own terms or to lose your mind and get locked up. I don t know really but I know that when you scroll through comments on here no one seems interested in what day to day life is like for someone like us whose lives are taken over by this.

I don t know anything is the fact of it all at the end of the day. The only thing I know for sure is that when someone says they have answers, or that the aliens told them things, or that they are an alien, or anything for sure about aliens or conspiracies or anything like that, you can be pretty sure that that person is full of BS and is trying to pull one over on you. That s the truth and maybe the only full truth that I know. Because if this happens to you, if this really happens to you, then you don t get answers. You don t get to understand. And you don t come forward and pretend to have the answers. When this happens to you you spend all your days feeling like garbage and you try to hide.

I ve had I don t know how many jobs over the years all at around minimum wage, making sandwiches, delivering pizza, filling shipping boxes, janitorial work, but I can t hold a job because of this. I couldn t finish college because of this and I barely finished high school if you want to know that fact of it. I hardly leave my house or go out in public, not because I think people will think I m crazy and not even because I m afraid of people but because I m so tired all the time. I know that I have trauma and I know that maybe the way I see these things is shaped by that and all of that. I know that but it doesn t change the fact this is the day to day reality. I miss my dad and I miss Diane and I even miss Coach and I hardly get through a day without thinking about Sam because I just have no one else in my life. All the time I m lonely and it hurts to be this alone.

So no I don t know how their machines work or how they travel here or where I ll be going with them or any of that. I don t know any of that and that makes me feel even worse because I have no just no control and no understanding about it. And even if I asked them or if they could tell me how could I know? And how could I explain it to anyone if anyone would listen anyway? I don t even know how cell phones work. How does an air conditioner work? How do they get air into the machine that puts air in your car tires? I don t know any of this stuff. How long have they been here? I don t know but I don t even know how long we have been here. Do they have any weaknesses? I don t know and if they did do you think they would tell me? Can they feel love? I don t know that for sure because how could I know that. Why did they choose July 18? I don t know the answer to that. I don t have any answers to these things and I m sick of having the questions. And I don t care that I m not coming back because I don t have anything here. I m so tired of the loneliness and the sadness of this place. So what. I m not afraid of them or of the government either because there s nothing they can do. Every moment of my life is the worst moment of my life.

I ll tell you what is frustrating is to see so many comments on here and not just on here but everywhere about conspiracy this and conspiracy that and you can see in their faces or in their words that they want to be a part of it and they want this experience. But you DO NOT want this experience. It s frustrating to see people who think they have figured something out because they stayed up late on a Wednesday night reading something on the web and now they think they understand or they ve figured something out. You re out of your mind if you think you can figure it all out. I m not the crazy one. And you won t get your answers from the government coverup report that s about to come out that will say Oh sure there s some unexplained stuff but we don t know about any aliens.

And I hate to break it to everyone, but they already made contact. They are here and they have been here and they are now in contact with humans. I ve seen many, many, many more of us up there on my last several trips and they weren t like me not like Coach or Sam these aren t abductees or whatever it is that we are. When you see an abductee up there we usually look either like they are leading us down the hallway in a dentists office or else we are throwing our arms around and screaming because we are so scared. But the people up there now are different. But now there are people up there who look like business men and military men. They are sitting up there on their own without being guarded, and they are having meetings, and they are watching something on screens and talking back like probably with people back on Earth. They are wearing like army uniforms and military jackets. I ve heard these people up there speaking in English and in languages that I don t understand but, I mean, I know that some of them were Chinese, and some were Japanese or Korean, and there were some that were French because I do recognize French. I ve seen people who look Arab and African and everything you can imagine. They are in contact with us. I know that the U.S. government is in contact with them because I ve seen American military up there and also because when the U.S. government men kidnapped me they asked me questions that they couldn t have just made up. They had information about the ships and about what they have done to me on those ships and about me, and the only way they could have gotten all that information was if they were also talking with the friends of friends or whatever you want to call them. And that was years ago, so I know that the government at least knew about them years ago. And you wonder what you ll learn from the report?

Whatever was planned for July is still going to happen so far as I know, but it has definitely changed. Something changed and I m pretty sure that s why this report is coming out, but I can t be sure about that. I ve heard Friends talking about a report for years and years but I didn t know it would happen this way. I don t know if the report that s coming out is to prepare us or if it s just a cover up. I don t know what it all will be on the 18th, either, except that Gina 2 and the Friends of Friends are leaving and someone else is coming and that whatever will happen on Earth is not colonization. I ve seen maps up there and it looks like on the 18th something will happen at least in western Africa, something in maybe China or around China, and in Wyoming or Colorado or Utah. It s hard for me to know where stuff is just looking at maps without the state and country borders on them but none of the maps up there have any of those lines so I m making educated guesses on those three spots.

I don t know for sure what the government report will be but I think that the point of it is misdirection. There s a big change in the program coming and the Friends are leaving, and that s one of the reasons why I m going too, I think. And something about that change I think might be really noticeable or destructive or something. There won t be answers in any report, just misdirections, that s my bet.

This took me a lot longer than I thought it would and it s too late to answer questions, but I don t know if I would want to. I can t tell you exactly what will happen on the 18th and I don t care anyway. Whatever it is I just don t care even if it is destructive or even if the people coming to replace the Friends of Friends are terrible and they colonize. I don t have the ability to care anymore because I m just tired and I ve had to accept my destiny. The only way I make it through my nights right now is telling myself that in a few weeks time I ll get to see Diane and make sure that she s ok. I m probably being stupid because they are probably going to do something bad to me, but it really can t be worse than this and I have no choice but to believe that this will work out for me. I can t make it through the night without believe that. And believe me I know how pathetic it sounds when I say that all I have to look forward to is seeing a girl who is practically like a niece or a distant cousin and who might not even remember me for all I know. She s been gone a long time and I know there are others of us that they have taken so I hope that she s met some friends and is happy wherever she is and I guess wherever it is that I am going and maybe there will be enough of us there that I can make some friends.

7 18
Goodbye

Many of you have sent me very nice messages and I thank you all. I appreciate that there are some nice people out there. For the most part people commenting here are very mean and not just to me but also to people who actually have mental illness. I am sorry that you all are so angry. I m not ill and I m not depressed. I am sad and I am lonely and I am spending the next two days eating food I like and drinking tea and coffee and beer and making the most of it. You re all being lied to and manipulated by hoaxers and people who want attention and money and to control you somehow. I don t want any part of that. I have sent proof of my story to two people I grew up with, including screenshots of this account. They are old email addresses so I don t know if they check those emails or not but if they do they will be the only two people who can verify this information. I will never come back to reddit or anywhere else. If anyone posts claiming to be me or to know me or to be in contact with me they are lying to you. Many of you will know the truth on the 18th and I hope you all are safe.
"""
    copyfull = text
    ind = len(copyfull) // 2
    copyhalf = copyfull[:ind]

    # Split the text into paragraphs using regex pattern
    #@paragraphs = re.split('(?<=\.|\?) ([^\.\?!])\1', text)
    paragraphs = text.split('\n')
    
    for paragraph in paragraphs:
        if paragraph != "" or paragraph.strip('\n') != "":  # Skip empty lines
            print("currently working on: ", paragraph)
            #input_ = f"Given the following input: `{paragraph}`, please provide me with the key concepts, people, ideas, places, history, 'factual information', etc, from the text. Also, make sure any value you use for a json key is an appropriate json key, eg hyphenated or single string with now spaces. Please provide me with a JSON representation of the breakdown you generate, and respond only with the json object, NOTHING ELSE, not even the tickmarks around the json object. It's extraordinarily important that you ensure that EVERY json key in your struct has no more than ONE word as the key. Make sure you also provide a 'summary' of the input text, too as one of your json keys and values. None of your json values should be booleans. All json should at least include the keys 'summary', 'concepts', 'people', 'places', 'ideas', and 'facts'. All of these types are arrays of strings, except 'summary', which is a string. The JSON you create will NEVER have any keys other than those specified, and you should fit all classifications and analysis into those json keys as appropriate. ."
            input_ = f"Given the following sentence: ```text {paragraph}```, and the following lore: ```text {copyhalf}```, please generate a QUESTION about the sentence, and an ANSWER to that QUESTION using info from the included LORE."
            output = query_ai(input_).content
            output = output.strip('```json')
            output = output.strip('```')
            output = output.strip('`')
            output = output.strip(' ')
            output = output.strip('\n')
            synthetic_data = output
            breaks = synthetic_data.split("ANSWER: ")
            if len(breaks) > 1:
                answer = breaks[1]
                question = breaks[0].split("QUESTION: ")[1]
            else:
                breaks = synthetic_data.split("Answer: ")
                answer = breaks[1]
                question = breaks[0].split("Question: ")[1]

            with open("synthetic_data3.json", "a") as fi:
                #data = json.dumps(synthetic_data).removeprefix('\\n')
                # js = json.loads(data)
                print("synth data was: ", synthetic_data)
                writejs = {
                    "sentence": paragraph,
                    "input": question,
                    "target": answer
                }
                fi.write(json.dumps(writejs) + ',\n')
        else:
            print("\n\nhit the code i DIDNT want to hit.")

if __name__ == "__main__":
    file_path = "data/taa.txt"
    process_file(file_path)
